import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Posts from "@/components/Posts";
import { useEffect } from "react";
import clsx from "clsx";
import PopularUsers from "@/components/PopularUsers";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="pageSectionStandartSize">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={clsx(styles.postsMain)}>
        <Posts />
        <PopularUsers />
      </div>
    </div>
  );
}
